### ISSUE TITLE
Trust minerva root in cointainer

### ISSUE THREAD

**Issue by dangernil** [Skatteetaten/terraform-nomad-minio#111]
## Feature description
Trust Minerva root in container

## Why is it needed?
Vault KMS requires SSL validation against minerva vault

## Checklist (after created issue)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by zhenik** [comment]
Open source projects should not contain any company certs. 
Also, certs are mounted to the docker image, and docker image is just a variable in the module.

I think we should close this issue and PR. WDYT @dangernil @claesgill @fredrikhgrelland ?
