### ISSUE TITLE
Support key rollover for root secret

### ISSUE THREAD

**Issue by lmjelstad** [Skatteetaten/terraform-nomad-minio#115]
## Feature description

Implement mechanism where root access/secretkey can be changed after deploying MinIO without losing (meta)data

## Why is it needed?

When changing credentials MinIO need both the old and new key to migrate data and to re-encrypt with the new key. 

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by fredrikhgrelland** [comment]
@lmjelstad This needs a justification in "Which is it needed?"
