### ISSUE TITLE
Backup/recovery mechanisms

### ISSUE THREAD

**Issue by pdmthorsrud** [Skatteetaten/terraform-nomad-minio#15]
Do we need a backup/recovery mechanism for MinIO, or would this be handled by Spectrum Scale in Minerva?

**Comment by zhenik** [comment]
relevant https://github.com/fredrikhgrelland/terraform-nomad-postgres/issues/10

**Comment by zhenik** [comment]
resolved in https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/31
