### ISSUE TITLE
UserStory[Security]: Generate password for minio from Vault 

### ISSUE THREAD

**Issue by Neha-Sinha2305** [Skatteetaten/terraform-nomad-minio#16]
### Description
As of today we use user provided screts to access minio, however, going forward we would like to generate these secrets from Vault. The [KV Secrets Engine](https://www.vaultproject.io/docs/secrets/kv) feature could be made use of to achieve this.

**Acceptance Criteria**

1. Remove the hardcoded **minio_access_key**, **minio_secret_key** . 
2. Generate on demand password with vault
3. Add tests
4. Add/update documentation

**Questions**
1. How should this be handled in the minio-client(mc)?
-- Set output variable in minio and use that in mc

**Discussion**
1. Code in vagrant-hashistack to enable KV secret engine

**Comment by Neha-Sinha2305** [comment]
@zhenik @pdmthorsrud : Should we use :
- [ ]  [KV Secrets Engine - Version 1](https://www.vaultproject.io/docs/secrets/kv/kv-v1)
OR
- [x]  [KV Secrets Engine - Version 2](https://www.vaultproject.io/docs/secrets/kv/kv-v2)

**Comment by zhenik** [comment]
I would recommend going for `v2`

**Comment by Neha-Sinha2305** [comment]
Code is being added to the following branch: [vault_gen_password](https://github.com/fredrikhgrelland/terraform-nomad-minio/tree/vault_gen_password)
