### ISSUE TITLE
Plugin to generate random strings

### ISSUE THREAD

**Issue by Neha-Sinha2305** [Skatteetaten/terraform-nomad-minio#23]
- If we decide to upstream this plugin to 00-poststart-example.yml of box.  Coupling with the specific plugin: https://github.com/sethvargo/vault-secrets-gen
- generating random string need a plugin (yes - this PR)
- if we decide to use this plugin, what are our requirements (security: algorithms, support of symbols like numbers-  case- special symbols, byte strength etc...) What if we decide chose another plugin for such a needs

_Originally posted by @zhenik in https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/19#issuecomment-696016656_

**Comment by Neha-Sinha2305** [comment]
@zhenik : Based on the changes done for issue #44 where we ended up using [ ansible Password lookup plugin ](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_lookup.html) for generating random strings rather than any specific plugin, I guess we can close this issue.
What do you think?

**Comment by zhenik** [comment]
@Neha-Sinha2305 agree
