### ISSUE TITLE
Update required nomad_provider version to the latest

### ISSUE THREAD

**Issue by Neha-Sinha2305** [Skatteetaten/terraform-nomad-minio#30]
We might need to update it to the latest. https://github.com/hashicorp/terraform-provider-nomad/releases/tag/v1.4.9 

Not sure that in current PR. Let's leave as it is, due to PR context

_Originally posted by @zhenik in https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/29#discussion_r497504208_

**Comment by zhenik** [comment]
vault also

**Comment by Neha-Sinha2305** [comment]
The update needs to be made in these two files:
https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/example/vagrant_box_example/main.tf
https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/template_example/example/standalone/main.tf
