### ISSUE TITLE
Refactor the minio and mc nomad job files

### ISSUE THREAD

**Issue by Neha-Sinha2305** [Skatteetaten/terraform-nomad-minio#37]

**Comment by zhenik** [comment]
@Neha-Sinha2305 is this one ~~duplicate~~ of https://github.com/fredrikhgrelland/terraform-nomad-minio/issues/28 ?

**Comment by Neha-Sinha2305** [comment]
Well, #28 revolves more around decoupling minio and mc, however in this issue, we could focus on as how we could for example extract this in a single variable :
https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/23e20f7cc08fd2fd0c7668a32aed7a6a834c59bf/conf/nomad/minio.hcl#L55-L60

And follow similar principles across other modules where needed. The scope of this issue is smaller than #28.

**Comment by claesgill** [comment]
@zhenik Is this still something we want to implement?

**Comment by zhenik** [comment]
I would say, on its current state(module) - `early development`, it is good enough to couple MC(minio-client)+MINIO(minio). Due to encapsulate bucket creation.

**Comment by claesgill** [comment]
> I would say, on its current state(module) - `early development`, it is good enough to couple MC(minio-client)+MINIO(minio). Due to encapsulate bucket creation.

Ok, should we close this or leave for now?

**Comment by zhenik** [comment]
> > I would say, on its current state(module) - `early development`, it is good enough to couple MC(minio-client)+MINIO(minio). Due to encapsulate bucket creation.
> 
> Ok, should we close this or leave for now?

let us close this one

**Comment by claesgill** [comment]
> > > I would say, on its current state(module) - `early development`, it is good enough to couple MC(minio-client)+MINIO(minio). Due to encapsulate bucket creation.
> > 
> > 
> > Ok, should we close this or leave for now?
> 
> let us close this one

Closing due to discussion above.
