### ISSUE TITLE
host_volume should be configurable

### ISSUE THREAD

**Issue by fredrikhgrelland** [Skatteetaten/terraform-nomad-minio#39]
master has implemented host_volumes, but it is mandatory in order to use the module.
That is too opinionated and we should allow for no host_volumes to exist on the nomad clients

**Comment by Neha-Sinha2305** [comment]
@fredrikhgrelland :+1:
Yeah, that's true!
So inorder to render flexibility, we need a switch that could turn on or off this feature say **minio_enable_host_volume** ?
And the switch needs to be upstreamed to the box as well.

Do you think we need to fix this in 0.1.0 release(scheduled for today) or  could we add it in a patch release next week?
Also we need to add a similar switch for postgres host volume feature as well to have it behave consistently across our modules?

**Comment by fredrikhgrelland** [comment]
@Neha-Sinha2305 before release 👍

**Comment by Neha-Sinha2305** [comment]
@fredrikhgrelland:
ok..will start working on this then.
The switch **minio_enable_host_volume** should have default value as **false**?
Are you ok with the name: **minio_enable_host_volume** or do we have a standard naming convention for switches?

**Comment by fredrikhgrelland** [comment]
default: false
name: use_host_volume ?
