### ISSUE TITLE
Code changes for tests to run seamlessly in gitlab

### ISSUE THREAD

**Issue by Neha-Sinha2305** [Skatteetaten/terraform-nomad-minio#48]
This issue is a placeholder for the changes we need to make so as the tests can be run seamlessly in gitlab.
One of the first changes that we would like to make is to the makefile:

- [x] [ifdef CI]( https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/7204c9f1b2790b0059c6a16891c8e9a80c1235fa/Makefile#L38
) can be changed to ifeq ($(GITHUB_ACTIONS),true)

**Comment by zhenik** [comment]
@vitaly-semenov FYI

**Comment by Neha-Sinha2305** [comment]
@vitaly-semenov :
- [x] The second thing to tackle is to provide env variables that are more inline with Minerva. This needs to be solved in the  [gitlab.ci.yml file](https://10.6.130.213/plattform/koin/demo-terraform-nomad-minio/-/blob/master/.gitlab-ci.yml) Before calling **make test**, the following needs to be done :

1. Create file **.env_override** 
2. echo the following values to the file :
```
consul_enterprise=true
nomad_enterprise=false
vault_enterprise=true
consul_acl=true
consul_acl_default_policy=deny
nomad_acl=true
vault_pki=true
```
3. make test

**Comment by Neha-Sinha2305** [comment]
Assigned this issue to rest of the team so everyone has same visibility in the progress of this task.

**Comment by vitaly-semenov** [comment]
I have tested changes in GitLab pipeline and all works fine. Links to pipeline and successful run:
[GitLab pipeline](https://gitlab.service.v2.minerva.loc/plattform/koin/demo-terraform-nomad-minio/-/blob/master/.gitlab-ci.yml)
[Build](https://gitlab.service.v2.minerva.loc/plattform/koin/demo-terraform-nomad-minio/-/jobs/5658)

**Comment by Neha-Sinha2305** [comment]
Closing this issue as the tests run fine in gitlab now.
