### ISSUE TITLE
Host volumes should be configurable.

### ISSUE THREAD

**Issue by fredrikhgrelland** [Skatteetaten/terraform-nomad-minio#58]
## Feature description
There is no way of choosing where this module puts its data.

## Why is it needed?
More than one module in one environment?

## Suggestion(s)/solution(s) [Optional]
- Configure volume names.
- Option to use mounts in addition to "volumes"

## Definition of done

volumes and mounts are fully configurable

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by claesgill** [comment]
This is fixed using the `nomad_host_volume` variable:
https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/main.tf#L33
