### ISSUE TITLE
Outdated documentation (example section)

### ISSUE THREAD

**Issue by zhenik** [Skatteetaten/terraform-nomad-minio#62]
## Current behaviour
The documentation section `example` does not show the new release example.

## Expected behaviour
The documentation section `example` is up to date accordingly latest release, and follow default behavior.

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by dangernil** [comment]
Closed with: https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/84

**Comment by claesgill** [comment]
Reopening: https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/88#issuecomment-725269091
