### ISSUE TITLE
template: template destination path escapes alloc directory

### ISSUE THREAD

**Issue by fredrikhgrelland** [Skatteetaten/terraform-nomad-minio#63]
## Checklist (after created issue)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by zhenik** [comment]
Could @fredrikhgrelland you elaborate please?

**Comment by claesgill** [comment]
@fredrikhgrelland Can you elaborate or close?

**Comment by fredrikhgrelland** [comment]
https://github.com/Skatteetaten/terraform-nomad-minio/commit/02dc571e1f1823d523889675e996f4b6ac4772ab
