### ISSUE TITLE
Proper rendering of credentials

### ISSUE THREAD

**Issue by dangernil** [Skatteetaten/terraform-nomad-minio#66]
## Feature description
As a user of the module we want proper render of credentials, without using vault provider

## Why is it needed?
To make it easier to use the module.

## Suggestion(s)/solution(s) [Optional]
Done in Presto module: https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto.hcl#L327

## Definition of done
- Rendering credentials in `.hcl` file

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
@dangernil Wrong feature description -> `As a user of the module we want proper render of credentials, without using vault provider`

Take a look at #22
