### ISSUE TITLE
dynamic destination for secrets

### ISSUE THREAD

**Issue by dangernil** [Skatteetaten/terraform-nomad-minio#76]
## Feature description
Have a dynamic variable for destination, etc: variable for user to define destination either local, secrets or other nomad directory.  

## Suggestion(s)/solution(s) [Optional]
``destination = "secrets/.envs"`` be ``destination = ${some_var}/.envs`` 
```
variable "secret_dir" {
  type        = string
  description = "Minio secret directory"
  default     = secret/minio
}
```

## Checklist (after created issue)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by zhenik** [comment]
I am not sure what do you mean here. 
Dynamic destination is possible under `/secrets/<here>` - predifined nomad directories for allocations
