### ISSUE TITLE
Increase memory allocation for consul sidecar proxy

### ISSUE THREAD

**Issue by karimacherradi** [Skatteetaten/terraform-nomad-minio#85]
## Feature description
Increase memory allocation for minio sidecar proxy
## Why is it needed?
Increase memory allocation
## Definition of done
Side car proxy services are running with more memory
## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Related to https://github.com/fredrikhgrelland/terraform-nomad-postgres/issues/56

**Comment by zhenik** [comment]
Pay attention to healthchecks after using `sidecar_task` stanza
