### ISSUE TITLE
Stay consistent with variable names among modules

### ISSUE THREAD

**Issue by zhenik** [Skatteetaten/terraform-nomad-minio#87]
## What is the issue?
Variables of one context among modules named differently.
https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/variables.tf#L95-L96 
```
vault_kv_access_key    = string,
vault_kv_secret_key    = string
```

while in the Postgres module, has different suffix `_name`
https://github.com/fredrikhgrelland/terraform-nomad-postgres/blob/master/variables.tf#L85-L86
```
    vault_kv_username_name = string,
    vault_kv_password_name = string
```

## Suggestion(s)/solution(s) [Optional]
**Use one naming convention**

```
vault_kv_field_<entity>
```
## Checklist (after created issue)
- [X] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by pdmthorsrud** [comment]
I believe the `vault_kv_<entity>_name` and `vault_kv_<entity>_value` for the key and value, respectively, for a KV-pair is a good way to go.

**Comment by zhenik** [comment]
I imagine that credentials stored in a vault kv path, might be way more complex. I would suggest, smth like
`vault_kv_<entrity>_fieldname` or `vault_kv_<entrity>_fieldkey`

Take a look at JSON representation here, where the `access_key` and `secret_key` are fields.

<img width="521" alt="Screenshot 2020-11-10 at 13 44 21" src="https://user-images.githubusercontent.com/15572799/98675702-e622c800-235a-11eb-9202-b1672f9d6c7d.png">

**Comment by pdmthorsrud** [comment]
> I imagine that credentials stored in a vault kv path, might be way more complex. I would suggest, smth like
> `vault_kv_<entrity>_fieldname` or `vault_kv_<entrity>_fieldkey`
> 
> Take a look at JSON representation here, where the `access_key` and `secret_key` are fields.
> 
> <img alt="Screenshot 2020-11-10 at 13 44 21" width="521" src="https://user-images.githubusercontent.com/15572799/98675702-e622c800-235a-11eb-9202-b1672f9d6c7d.png">

Not quite sure I got that, but I'm down to call it fieldname and fieldkey!

**Comment by zhenik** [comment]
We can use naming from Vault cli, where you can specify [`-field`](https://www.vaultproject.io/docs/commands/kv/get#field)

Example:
```
vault kv get -field=access_key secret/data/random-string/minio
```

`vault_kv_<entrity>_field` <- like this

**Comment by pdmthorsrud** [comment]
> We can use naming from Vault cli, where you can specify [`-field`](https://www.vaultproject.io/docs/commands/kv/get#field)
> 
> Example:
> 
> ```
> vault kv get -field=access_key secret/data/random-string/minio
> ```
> 
> `vault_kv_<entrity>_field` <- like this

Good idea, I like that

**Comment by zhenik** [comment]
Options
- [x] `vault_kv_field_<entity>`
- [ ] `vault_kv_<entity>_field`
- [ ] `vault_kv_<entity>_name`
- [ ] `vault_kv_<entity>_fieldname`

**Comment by claesgill** [comment]
> Options
> 
> * [ ]  `vault_kv_field_<entity>`
> * [ ]  `vault_kv_<entity>_field`
> * [ ]  `vault_kv_<entity>_name`
> * [ ]  `vault_kv_<entity>_fieldname`

Voting for `vault_kv_field_<entity>` 🙋
